### PR TITLE
Workflow v1

### PR DESCRIPTION
**Pull request by simonwa7**

### CODE REVIEW

**Review by martamau — COMMENTED** [review]
we are not including the daemon as it's not supported in v1 yet?

**Comment by simonwa7** [comment]
Not sure yet - a good question for @max-radin once he's back, but we can always push a new update next week

**Comment by martamau** [comment]
Then I'd probably merge this and add a story for the daemon for next week? @simonwa7

**Comment by simonwa7** [comment]
Yep! That sounds like a good plan to me: https://www.pivotaltracker.com/story/show/175063962

**Comment by martamau** [comment]
I'll approve the PR then :) love the story ahah

**Review by martamau — APPROVED** [review]

**Pull request merged**
